import "./index.css";
import NavMenu from "@/components/NavMenu";
import Provider from "@/contexts/Provider";
import Footer from "@/components/Footer";
import Alert from "@/components/Alert/Alert";
import { primary } from "@/utils/fonts";
// import { cookies } from "next/dist/client/components/headers";
import { cookies } from "next/headers";
import apiUrl from "@/utils/apiUrl";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const res = await fetch(apiUrl + "/users/me", {
		headers: {
			Cookie: cookies(),
		},
	});
	const data = await res.json();
	return (
		<html lang="en">
			<body className={primary.className}>
				<Provider>
					<NavMenu userData={res.ok && res.status ? data : null} />
					<Alert />
					<div className="container">{children}</div>
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
